template: |
  ## Changes
  $CHANGES

exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'enhancement'
    branch:
      - '/refactor\/.+/'
      - '/perf\/.+/'
  - label: 'feature'
    branch:
      - '/feat\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'maintenance'
    files:
      - '*.md'
      - '*.txt'
      - '*.png'
      - '*.yml'
    title:
      - '/chore/i'
      - '/docs/i'
    branch:
      - '/chore\/.+/'
      - '/docs\/.+/'
  - label: 'ci'
    files:
      - '.github/*'
  - label: 'test'
    branch:
      - '/test\/.+/'
  - label: 'hotfix'
    branch:
      - '/hotfix\/.+/'
  - label: 'lua-code-changed'
    files:
      - '*.lua'